###
#  rakefile with rails tasks
#    precompile assets
#    use $ rake -f script/Rakefile assets:precompile RACK_ENV=production

#  check tasks
#    use $ rake -f script/Rakefile -T

puts "main:"
puts $0



require_relative '../lib/sportweb/environment.rb'

Rails.application.load_tasks
